Home header
basnetlaxmi/hello-microverse pull request #1
Opened 2021-08-10 12:26 UTC by basnetlaxmi

## Home Header 
In this version : 
⚪ I added h1 text in index.html.
⚪ I added style for h1 of index.html with style.css.

2021-08-10 14:56 UTC, AshakaE requested changes
### Hi @basnetlaxmi  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on to go to the next project but you are almost there!

#  Required Changes ♻️ 🚧
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 14:56 UTC, AshakaE commented on test.md
> +# This file should be ignored by git.
- [ ] Please make sure this file is properly ignored from git before making a `git push` 🙏

2021-08-11 04:34 UTC, DanteAlonsoHT requested changes
<h1>Status: Changes Required 🚫 ♻️  </h1>

Hi @basnetlaxmi, 

Nice work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet, please follow the next changes required in order to improve your project.

 ## Required Changes ♻️

_Check the comments under the review._

<hr>

I know you have the capabilities enough to finish these changes required in time 😉 

Happy coding!👏👏 😉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 04:34 UTC, DanteAlonsoHT commented on README.md
> +![screenshot](./images/pic.png)
This image is not working, you should remove it or fix it as you want.

- [ ] Remove or Fix the image in your README file.

2021-08-11 04:34 UTC, DanteAlonsoHT commented on README.md
> +
Remove "Setup", "Install", "Usage", "Run tests" and "Deployment" sections if you are not using them.

- [ ] Remove empty sections.

2021-08-11 04:34 UTC, DanteAlonsoHT commented on README.md
> +> This is a site showing hello microverse text as a header.
I know you did a good effort creating your description for your project, but I strongly recommend you adding a much better description, in you want a reference, 3 or more lines can be good, you can explain what you did, what kind of technologies you used, what is the scope, and so on.

- [ ] Improve your description for your project.

2021-08-11 04:34 UTC, DanteAlonsoHT commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
You should leave only one author in this solo project, and please add the links for your own social media.

- [ ] Remove extra author information.
- [ ] Add your own social media links in this section of your README file.

2021-08-11 08:40 UTC, dasileker approved these changes
### **Hi @basnetlaxmi**

### **Project Approved ✅** 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 08:42 UTC, merged